services:
  db:
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: gamparts
      POSTGRES_PASSWORD: gamparts_dev
      POSTGRES_DB: gamparts
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
